### ISSUE TITLE
Ryujinx setup

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [lantus/chocolate-doom-nx#2]
so i tried to setup ryujinx to run this but it wont do so can you tell me the file structure for ryufs

**Comment by Gamedev1909** [comment]
only thr nso loads the nro wont

**Comment by prankard** [comment]
Hey, I'm also having issues running these .nro on the switch and on the emulator.
Does this port run without external wad files? I've tried running with a few doom1.wad, doom2.wad and doom.wad alongside the .nro
I'm testing on the committed build in ./release (and have also tried with my build).

Here is the output from the emulator:
```
PS C:\devkitPro\tutorial\chocolate-doom-nx\release\publish> .\Ryujinx.exe ..\doom.nro
Loading as homebrew.
00:00:00.053 | 0001 Loader LoadProgram: Image base at 0x0000000008000000.
00:00:00.322 | 0006 ServiceAm GetAppletResourceUserId: Stubbed.
00:00:00.342 | 0006 ServiceAm AcquireForegroundRights: Stubbed.
00:00:00.347 | 0006 ServiceAm SetFocusHandlingMode: Stubbed.
00:00:00.360 | 0006 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed.
00:00:00.376 | 0006 ServiceAm SetOperationModeChangedNotification: Stubbed.
00:00:00.380 | 0006 ServiceAm SetPerformanceModeChangedNotification: Stubbed.
00:00:00.426 | 0006 Hid ShMemMap: HID shared memory successfully mapped to 0x0000000008411000!
00:00:00.432 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:00.434 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:00.435 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:00.435 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:00.436 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:00.439 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:00.440 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:00.441 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:02.043 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:02.046 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:02.047 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:02.047 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:02.048 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:02.048 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:02.049 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:02.049 | 0006 ServiceHid SetNpadJoyAssignmentModeDual: Stubbed.
00:00:02.101 | 0006 Loader ExitProcess: HbAbi NextLoadPath
00:00:02.106 | 0006 Loader Dispose: Process 0 waiting all threads terminate...
00:00:02.118 | 0006 Loader Dispose: Process 0 exiting...
```

It runs, gets a black screen window and then closes.
Testing on swtich 5.0.2 and Ryujinx 1.0.692

**Comment by lantus** [comment]
RyuJinx emulates the SD card file system and usually puts this in c:\users\<user name>\AppData\Roaming\RyuFS\sdmc . You need to place your doom.wad or doom2.wad in this folder as well as the chocolate-doom.cfg

that should work for you

**Comment by prankard** [comment]
Thanks for this, I've gotten the emulator all up and running now :)

I added either (doom.wad, doom1.wad or doom2.wad) into:
%appdata%\RyuFs\sdmc
And then also created an empty folder called 'tmp' to get it to run.

Just having issues trying to get it running via the switch. It keeps closing currently but will report back once I've figured out how to debug and see some error log, I'm sure it's a case of a missing file as it runs via the emulator fine.

**Comment by lantus** [comment]
on a real switch do exactly the same thing you did above in your sdmc:/switch partition. I create a folder called Doom and put everything in it (ie doom.nro, the doom 1 or 2 wad file, tmp subfolder and the chocolate-doom.cfg file)

**Comment by prankard** [comment]
Thanks for this. Can confirm it's all compiling and working.
I had issues with my sd card causing all sorts of problems. Bought a new one and I'm dooming.
I've added instructions for the emulator for the readme as a pull request so you can go ahead and close this issue.
