### ISSUE TITLE
controls

### ISSUE THREAD

**Issue by XxcglezxX** [lantus/chocolate-doom-nx#3]
is there any way to edit the controls? i just want a way to sprint

**Comment by lantus** [comment]
if you want to sprint open up the chocolate-doom.cfg file

add this entry:

joyb_speed 8

and retry. it should map it to the L Trigger

**Comment by XxcglezxX** [comment]
ok thanks

**Comment by XxcglezxX** [comment]
it didnt work

**Comment by XxcglezxX** [comment]
@lantus it didnt work

**Comment by prankard** [comment]
I was playing around with this the other day. Try these two configs:
https://github.com/prankard/chocolate-doom-nx/blob/readme-update/release/chocolate-doom.cfg
https://github.com/prankard/chocolate-doom-nx/blob/readme-update/release/default.cfg

**Comment by XxcglezxX** [comment]
@prankard it worked thanks
