### ISSUE TITLE
Chocolate Doom gives no display on emulation, and immediately closes on Real Hardware. 

### ISSUE THREAD

**Issue by IncognitoJoe** [lantus/chocolate-doom-nx#6]
The pre-built nro does the same as my build, I am going to attempt one of your forks just to see. I will post a video later.

- Firmware 5.1.0
- Using CTCasr/Atmosphere and ReiNX
- Using the emulator from the video

**Comment by lantus** [comment]
did you drop a WAD file in the same folder as the .nro ?

**Comment by IncognitoJoe** [comment]
I did and had all 4 files in the Doom folder... it may just be that my Doom wad is bad.... if it is Doom 1, does it have to be named doom1.wad? And if it is the shareware version, will it still work?

**Comment by lantus** [comment]
shareware will work yes. I havent tested on 5.10 yet though

**Comment by IncognitoJoe** [comment]
What is you've FW, because if you are <3.0.1 I know that certain things don't work

**Comment by lantus** [comment]
create a folder called 'tmp' in the same folder as the .nro . that may be the issue

**Comment by IncognitoJoe** [comment]
Sorry for not messaging back... the fix did not work. I will send info in 1-2 days with video of Doom crashing on my Switch

**Comment by lantus** [comment]
update to the 1.02 overwrite everything
